# Regresión lineal en Python
## El paquete scikit-learn para regresión lineal y la selección de rasgos

In [2]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression  #Ahora hacer regresion con este paquete

In [3]:
data = pd.read_csv("../datasets/ads/Advertising.csv")

In [4]:
feature_cols = ["TV", "Radio", "Newspaper"]

In [5]:
X = data[feature_cols]
Y = data["Sales"]

In [6]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, 2, step=1)
selector = selector.fit(X,Y)

In [7]:
selector.support_   #La variable Tv y la variable Radio quedan seleccionadas

array([ True,  True, False])

In [8]:
selector.ranking_   #TV y Radio quedan en el rango 1 de importancia para el modelo

array([1, 1, 2])

In [10]:
X_pred = X[["TV", "Radio"]]  #Elegimos las variables significativas obtenidas anteriormente

In [11]:
lm = LinearRegression()
lm.fit(X_pred, Y)     #Obtenemos el modelo de ajuste de regresion lineal para nuestras 2 variables elegidas

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [12]:
lm.intercept_    # Coeficiente para el intercepto (B0)

2.9210999124051362

In [13]:
lm.coef_    #Coeficientes para TV y Radio respectivamente

array([0.04575482, 0.18799423])

In [14]:
lm.score(X_pred, Y)  #coeficiente R cuadrado

0.8971942610828956