#  K means

In [1]:
import numpy as np

In [2]:
#Genero datos aleatorios: 30 individuos de 3 features
data = np.random.random(90).reshape(30,3)
data

array([[0.46706312, 0.70400284, 0.55081113],
       [0.18240919, 0.96958253, 0.85120857],
       [0.67746878, 0.05564808, 0.8689322 ],
       [0.79096291, 0.32842966, 0.45187536],
       [0.32349601, 0.1323071 , 0.99834664],
       [0.65333239, 0.94931241, 0.31193298],
       [0.25822225, 0.9854903 , 0.54332611],
       [0.30615897, 0.01297012, 0.30272322],
       [0.55911324, 0.72856546, 0.38273906],
       [0.68177786, 0.50214662, 0.97537523],
       [0.75416811, 0.7541229 , 0.55908288],
       [0.82126034, 0.22957444, 0.15884192],
       [0.5072319 , 0.01832089, 0.61728992],
       [0.91676542, 0.82018103, 0.58007436],
       [0.79454816, 0.74020135, 0.1613427 ],
       [0.3300317 , 0.35953343, 0.05468748],
       [0.08884278, 0.66890987, 0.44707731],
       [0.95685007, 0.91550869, 0.14326787],
       [0.67818724, 0.0500608 , 0.42258649],
       [0.63018951, 0.98693535, 0.61514651],
       [0.7451097 , 0.52363884, 0.38258853],
       [0.59303946, 0.71926722, 0.13249864],
       [0.

In [5]:
#Como quiero dividir el conjunto de datos en 2 clusters, elijo 2 elementos para convertirlos en centroides:
centro1 = np.random.choice(range(len(data)))
centro2 = np.random.choice(range(len(data)))

In [8]:
#Creo arreglo con mis dos centroides elegidos
centros = np.vstack([data[centro1],data[centro2]])
centros

array([[0.08884278, 0.66890987, 0.44707731],
       [0.91676542, 0.82018103, 0.58007436]])

**Para hacer clusters puedo usar las funciones vq o kmeans de scipy**

In [11]:
from scipy.cluster.vq import vq, kmeans

In [12]:
clusters = vq(data,centros)
clusters #devuelve dos arreglos, uno donde especifica a qué cluster pertenece cada observacion
         #y el otro especifica la distancia de cada elemento al baricentro de su cluster al que pertenece

(array([0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
        0, 0, 1, 0, 0, 0, 1, 0]),
 array([0.39375481, 0.5123288 , 0.85159402, 0.52352714, 0.80430253,
        0.3974565 , 0.37172086, 0.70591883, 0.41862837, 0.55913131,
        0.17675465, 0.73169265, 0.79201503, 0.        , 0.44347492,
        0.55484742, 0.        , 0.44888089, 0.82146646, 0.33341088,
        0.39547897, 0.56152125, 0.31380873, 0.31995294, 0.56158466,
        0.50767341, 0.39122136, 0.19682876, 0.53545713, 0.51144027]))

**A la funcion kmeans se le pasa el dataset normalizado y, ya sea los centroides para iniciar proceso de clusterizacion(como el primer ejemplo a continuacion) o el numero de clusters que se desean(como el segundo ejemplo a continuacion)**

In [18]:
kmeans(data,centros)  #Devuleve un arreglo donde especifica los centroides resultantes al final del proceso
# y un escalar = (la suma de los cuadrados de las distancias de cada punto a su centroide correspondiente)/(la suma de los cuadrados de las distancias de cada punto al baricentro global del sistema)

(array([[0.39268115, 0.45662529, 0.59783961],
        [0.74684903, 0.69961249, 0.35267189]]), 0.3752014771479203)

In [20]:
kmeans(data,2) 


(array([[0.53554277, 0.25001526, 0.63604507],
        [0.51260147, 0.7718482 , 0.40998574]]), 0.34752478741784804)